// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpLvvkZhie1HYhkxghoKEaI_Ojy39O1ew',
    appId: '1:937753507024:web:47f6fdf48d245a40a2dad5',
    messagingSenderId: '937753507024',
    projectId: 'documentauth-652bc',
    authDomain: 'documentauth-652bc.firebaseapp.com',
    storageBucket: 'documentauth-652bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz3g3fUqOFr_tElSgfJd8EsPIf4nXLesA',
    appId: '1:937753507024:android:435b39e37bcd8e09a2dad5',
    messagingSenderId: '937753507024',
    projectId: 'documentauth-652bc',
    storageBucket: 'documentauth-652bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFVnmG00Meq3y9eupwUP0zTJqBtNbRY10',
    appId: '1:937753507024:ios:c9f90f5bdd3633f8a2dad5',
    messagingSenderId: '937753507024',
    projectId: 'documentauth-652bc',
    storageBucket: 'documentauth-652bc.appspot.com',
    iosBundleId: 'com.example.documentauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFVnmG00Meq3y9eupwUP0zTJqBtNbRY10',
    appId: '1:937753507024:ios:3ad85081d51db3fba2dad5',
    messagingSenderId: '937753507024',
    projectId: 'documentauth-652bc',
    storageBucket: 'documentauth-652bc.appspot.com',
    iosBundleId: 'com.example.documentauth.RunnerTests',
  );
}
